/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAdmetRouteImport } from './routes/app.admet'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppDtiRouteImport } from './routes/app.dti'
import { Route as AppExplainabilityRouteImport } from './routes/app.explainability'
import { Route as AppHistoryRouteImport } from './routes/app.history'
import { Route as AppMlflowRouteImport } from './routes/app.mlflow'
import { Route as AppModelsRouteImport } from './routes/app.models'
import { Route as AppRecommendationRouteImport } from './routes/app.recommendation'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppSideEffectsRouteImport } from './routes/app.side-effects'
import { Route as AppSimilarityRouteImport } from './routes/app.similarity'
import { Route as AppToxicityRouteImport } from './routes/app.toxicity'
import { Route as AppVisualizationRouteImport } from './routes/app.visualization'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdmetRoute = AppAdmetRouteImport.update({
  id: '/admet',
  path: '/admet',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppDtiRoute = AppDtiRouteImport.update({
  id: '/dti',
  path: '/dti',
  getParentRoute: () => AppRoute,
} as any)
const AppExplainabilityRoute = AppExplainabilityRouteImport.update({
  id: '/explainability',
  path: '/explainability',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppMlflowRoute = AppMlflowRouteImport.update({
  id: '/mlflow',
  path: '/mlflow',
  getParentRoute: () => AppRoute,
} as any)
const AppModelsRoute = AppModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AppRoute,
} as any)
const AppRecommendationRoute = AppRecommendationRouteImport.update({
  id: '/recommendation',
  path: '/recommendation',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppSideEffectsRoute = AppSideEffectsRouteImport.update({
  id: '/side-effects',
  path: '/side-effects',
  getParentRoute: () => AppRoute,
} as any)
const AppSimilarityRoute = AppSimilarityRouteImport.update({
  id: '/similarity',
  path: '/similarity',
  getParentRoute: () => AppRoute,
} as any)
const AppToxicityRoute = AppToxicityRouteImport.update({
  id: '/toxicity',
  path: '/toxicity',
  getParentRoute: () => AppRoute,
} as any)
const AppVisualizationRoute = AppVisualizationRouteImport.update({
  id: '/visualization',
  path: '/visualization',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/admet': typeof AppAdmetRoute
  '/app/admin': typeof AppAdminRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/dti': typeof AppDtiRoute
  '/app/explainability': typeof AppExplainabilityRoute
  '/app/history': typeof AppHistoryRoute
  '/app/mlflow': typeof AppMlflowRoute
  '/app/models': typeof AppModelsRoute
  '/app/recommendation': typeof AppRecommendationRoute
  '/app/reports': typeof AppReportsRoute
  '/app/side-effects': typeof AppSideEffectsRoute
  '/app/similarity': typeof AppSimilarityRoute
  '/app/toxicity': typeof AppToxicityRoute
  '/app/visualization': typeof AppVisualizationRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/admet': typeof AppAdmetRoute
  '/app/admin': typeof AppAdminRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/dti': typeof AppDtiRoute
  '/app/explainability': typeof AppExplainabilityRoute
  '/app/history': typeof AppHistoryRoute
  '/app/mlflow': typeof AppMlflowRoute
  '/app/models': typeof AppModelsRoute
  '/app/recommendation': typeof AppRecommendationRoute
  '/app/reports': typeof AppReportsRoute
  '/app/side-effects': typeof AppSideEffectsRoute
  '/app/similarity': typeof AppSimilarityRoute
  '/app/toxicity': typeof AppToxicityRoute
  '/app/visualization': typeof AppVisualizationRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/admet': typeof AppAdmetRoute
  '/app/admin': typeof AppAdminRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/dti': typeof AppDtiRoute
  '/app/explainability': typeof AppExplainabilityRoute
  '/app/history': typeof AppHistoryRoute
  '/app/mlflow': typeof AppMlflowRoute
  '/app/models': typeof AppModelsRoute
  '/app/recommendation': typeof AppRecommendationRoute
  '/app/reports': typeof AppReportsRoute
  '/app/side-effects': typeof AppSideEffectsRoute
  '/app/similarity': typeof AppSimilarityRoute
  '/app/toxicity': typeof AppToxicityRoute
  '/app/visualization': typeof AppVisualizationRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/admet'
    | '/app/admin'
    | '/app/analytics'
    | '/app/dti'
    | '/app/explainability'
    | '/app/history'
    | '/app/mlflow'
    | '/app/models'
    | '/app/recommendation'
    | '/app/reports'
    | '/app/side-effects'
    | '/app/similarity'
    | '/app/toxicity'
    | '/app/visualization'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/app/admet'
    | '/app/admin'
    | '/app/analytics'
    | '/app/dti'
    | '/app/explainability'
    | '/app/history'
    | '/app/mlflow'
    | '/app/models'
    | '/app/recommendation'
    | '/app/reports'
    | '/app/side-effects'
    | '/app/similarity'
    | '/app/toxicity'
    | '/app/visualization'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/admet'
    | '/app/admin'
    | '/app/analytics'
    | '/app/dti'
    | '/app/explainability'
    | '/app/history'
    | '/app/mlflow'
    | '/app/models'
    | '/app/recommendation'
    | '/app/reports'
    | '/app/side-effects'
    | '/app/similarity'
    | '/app/toxicity'
    | '/app/visualization'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admet': {
      id: '/app/admet'
      path: '/admet'
      fullPath: '/app/admet'
      preLoaderRoute: typeof AppAdmetRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dti': {
      id: '/app/dti'
      path: '/dti'
      fullPath: '/app/dti'
      preLoaderRoute: typeof AppDtiRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/explainability': {
      id: '/app/explainability'
      path: '/explainability'
      fullPath: '/app/explainability'
      preLoaderRoute: typeof AppExplainabilityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mlflow': {
      id: '/app/mlflow'
      path: '/mlflow'
      fullPath: '/app/mlflow'
      preLoaderRoute: typeof AppMlflowRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/models': {
      id: '/app/models'
      path: '/models'
      fullPath: '/app/models'
      preLoaderRoute: typeof AppModelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/recommendation': {
      id: '/app/recommendation'
      path: '/recommendation'
      fullPath: '/app/recommendation'
      preLoaderRoute: typeof AppRecommendationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/side-effects': {
      id: '/app/side-effects'
      path: '/side-effects'
      fullPath: '/app/side-effects'
      preLoaderRoute: typeof AppSideEffectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/similarity': {
      id: '/app/similarity'
      path: '/similarity'
      fullPath: '/app/similarity'
      preLoaderRoute: typeof AppSimilarityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/toxicity': {
      id: '/app/toxicity'
      path: '/toxicity'
      fullPath: '/app/toxicity'
      preLoaderRoute: typeof AppToxicityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/visualization': {
      id: '/app/visualization'
      path: '/visualization'
      fullPath: '/app/visualization'
      preLoaderRoute: typeof AppVisualizationRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdmetRoute: typeof AppAdmetRoute
  AppAdminRoute: typeof AppAdminRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppDtiRoute: typeof AppDtiRoute
  AppExplainabilityRoute: typeof AppExplainabilityRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppMlflowRoute: typeof AppMlflowRoute
  AppModelsRoute: typeof AppModelsRoute
  AppRecommendationRoute: typeof AppRecommendationRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSideEffectsRoute: typeof AppSideEffectsRoute
  AppSimilarityRoute: typeof AppSimilarityRoute
  AppToxicityRoute: typeof AppToxicityRoute
  AppVisualizationRoute: typeof AppVisualizationRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdmetRoute: AppAdmetRoute,
  AppAdminRoute: AppAdminRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppDtiRoute: AppDtiRoute,
  AppExplainabilityRoute: AppExplainabilityRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppMlflowRoute: AppMlflowRoute,
  AppModelsRoute: AppModelsRoute,
  AppRecommendationRoute: AppRecommendationRoute,
  AppReportsRoute: AppReportsRoute,
  AppSideEffectsRoute: AppSideEffectsRoute,
  AppSimilarityRoute: AppSimilarityRoute,
  AppToxicityRoute: AppToxicityRoute,
  AppVisualizationRoute: AppVisualizationRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
